"""Add knowledge_bases table and update datasources

Revision ID: 3c5436ffe6ef
Revises: 609042bc490f
Create Date: 2025-10-16 03:34:18.155919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c5436ffe6ef'
down_revision: Union[str, None] = '609042bc490f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'calendar_settings', ['id'])
    op.add_column('datasources', sa.Column('knowledge_base_id', sa.Integer(), nullable=False))
    op.alter_column('datasources', 'collection_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'datasources', ['id'])
    op.create_foreign_key(None, 'datasources', 'knowledge_bases', ['knowledge_base_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'datasources', type_='foreignkey')
    op.drop_constraint(None, 'datasources', type_='unique')
    op.alter_column('datasources', 'collection_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('datasources', 'knowledge_base_id')
    op.drop_constraint(None, 'calendar_settings', type_='unique')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
