"""add_task_id_to_datasource

Revision ID: 6d2a2206e534
Revises: 3c5436ffe6ef
Create Date: 2025-10-17 01:40:07.133999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2a2206e534'
down_revision: Union[str, None] = '3c5436ffe6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasources', sa.Column('task_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'knowledge_bases', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_bases', type_='unique')
    op.drop_column('datasources', 'task_id')
    # ### end Alembic commands ###
